### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by skirpichenko** [guestwalk/libffm#1]
Hello,

Thank you for your excellent method, software and description. 

I faced a problem trying to employ the libffm in my ML task. I am getting segmentation fault when using it with cross-validation option. Here are my setup and data:
Ubuntu 13.10
~/libffm$ ./ffm-train -k 5 -t 30 -r 0.03 -v 2 data.txt
fold      logloss
   0       0.1080
Segmentation fault (core dumped)

The data.txt can be downloaded here https://drive.google.com/open?id=0B9HyQ7ZccW4-VFE0VWtxUHF2R3c

The problem arises only when working with big data files like that. If you cut it to 100K lines (it is around 250K lines) everything get OK.

Regards,
Sergey

**Comment by guestwalk** [comment]
Thanks for reporting the issue. Will fix the bug soon.

**Comment by maybeluo** [comment]
I met the same question too. The input file was generated by "svm-scale" of libsvm (thus I believe the format is correct). The input file has 30k lines, 6k columns at most.

The OS I used was Debian wheezy with g++ 4.7

Thanks.

**Comment by guestwalk** [comment]
Thanks for the bug report! I have fixed it. Also sorry for the delay, I forgot this issue actually..

**Comment by skirpichenko** [comment]
Thanks!

**Comment by bishwarup307** [comment]
Hi guestwalk,

I just downloaded your repository and tried to execute my file (svmlight format) through ffm-train - I get the same error. Could you please shed some light on how the issue can be negated?

Thanks,
Bishwarup

**Comment by guestwalk** [comment]
Have you converted it to FFM format? If not please see README. Thanks.

**Comment by bishwarup307** [comment]
Thanks for your reply @guestwalk . Following your suggestion I could address the issue I reported. However, now my tr_logloss and va_logloss comes out to be 'nan' for all the iterations. Could you please give me some idea of possible causes for that. 

Thanks in advance,
Bishwarup

**Comment by guestwalk** [comment]
It's hard to say. Indeed NAN sometimes happens in some data sets. (For example, NLP data sets) I think if you can mail me a tiny data set that can lead to NAN it would be easier to investigate. Thanks.

**Comment by rajanandthakur** [comment]
@guestwalk I am still getting this issue. I installed libFFM today only. Ubuntu 14.04. data is large. snapshot of 1st 2 lines of data is below 

0 ad_id:1:1 document_id_x:151090:1 platform:2:1 category_id:1209:1 confidence_level_x:confidence_level_x:0.92 confidence_level_y:confidence_level_y:0.522604071891343 source_id:3877:1 publisher_id:789:1 topic_id:117:1 confidence_level:confidence_level:0.364758527021341 document_id_y:6614:1 campaign_id:1:1 advertiser_id:7:1 country:US:1
0 ad_id:1:1 document_id_x:1983857:1 platform:1:1 category_id:1205:1 confidence_level_x:confidence_level_x:0.92 confidence_level_y:confidence_level_y:0.931621398620803 source_id:4406:1 publisher_id:538:1 topic_id:26:1 confidence_level:confidence_level:0.199699197834132 document_id_y:6614:1 campaign_id:1:1 advertiser_id:7:1 country:US:1
