### ISSUE TITLE
“-nan” value appeared during training

### ISSUE THREAD

**Issue by lxjhk** [guestwalk/libffm#11]
When I was training the model, the first few iterations worked fine but subsequent iterations returned "-nan" for the log losses of training and validating data sets.

Any ideas what went wrong? 

![image](https://cloud.githubusercontent.com/assets/9475863/21545202/8cf78c64-ce10-11e6-80d7-e277937e4e58.png)

Sample of the data used for training:

1 0:400492:1 1:977206:1 2:861366:1 3:223345:1 4:4:0.0 5:5:9567.0 6:6:31835.0 7:7:0.300471105528 8:8:0.0 9:9:0.0 10:35822:1 11:486386:1 12:528723:1 13:662860:1 14:990282:1 15:406964:1 16:698517:1 17:585048:1 18:18:0.38219606197 19:19:0.125217833586 20:20:0.438929013305 21:21:0.216453092359 22:923220:1 23:63477:1 24:216531:1 25:461117:1
                                                                                                
0 0:400492:1 1:203267:1 2:861366:1 3:223345:1 4:4:0.0 5:5:1642.0 6:6:9441.0 7:7:0.173830192674 8:8:0.0 9:9:0.0644 10:709579:1 11:486386:1 12:528723:1 13:662860:1 14:778015:1 15:581435:1 16:698517:1 17:181797:1 18:18:0.581693006318 19:19:0.097000178732 20:20:0.367630745198 21:21:0.182764132116 22:923220:1 23:63477:1 24:216531:1 25:461117:1

**Comment by guestwalk** [comment]
I tried it in the latest version and do not see the nan anymore. If you still see the issue please reopen again. Thanks.

**Comment by b03902043** [comment]
I use libffm to train YAHOO R6B data, but the nan appear during training. However, the @ianlini 's fork repo wouldn't occur nan. Can you try that dataset with current libffm again?
