### ISSUE TITLE
viewing the model

### ISSUE THREAD

**Issue by shgidi** [guestwalk/libffm#17]
I've used this pacakge a few months, ago, and I remember I was able to do $head model, and to see the model weights.
It seems that the model is now encoded somehow (binarized?) am I correct? is there a way to see the model as before?

**Comment by guestwalk** [comment]
Yes, we store binary format now because the text format is too slow. We will provide a tool to view the model in the next major release, but for now there is no way to view the model. If you have such need, please use the previous version (v114).
