### ISSUE TITLE
ffm-train not found

### ISSUE THREAD

**Issue by JoshuaC3** [guestwalk/libffm#3]
Hi, I am trying to use libffm on ubuntu 16.04. I have C++11 and OpenMP installed via apt-get, downloaded libffm and did make. I am in the libffm dir and ran and got the following.

```
josh:~/libffm-master$ ffm-train bigdata.tr.txt model
ffm-train: command not found
```

When I check the `dir` you can see it is there

```
josh@josh-HP-ZBook-17-G2:~/libffm-master$ dir
bigdata.te.txt	ffm.cpp  ffm-predict	  ffm-train.cpp  README
bigdata.tr.txt	ffm.h	 ffm-predict.cpp  Makefile
COPYRIGHT	ffm.o	 ffm-train	  Makefile.win
```
Any help would be great. Thanks.

**Comment by guestwalk** [comment]
I guess you should try: $ ./ffm-train bigdata.tr.txt model

**Comment by JoshuaC3** [comment]
This worked. Many thanks
