### ISSUE TITLE
Features with multiple fields in `bigdata.tr.txt`

### ISSUE THREAD

**Issue by Hydrotoast** [guestwalk/libffm#4]
Hi,

It seems like `bigdata.tr.txt` has feature `2739` with multiple fields (`5` and `13`) in lines `21`, `36`, and `88`. Shouldn't fields be unique per feature?

**Comment by Hydrotoast** [comment]
Also feature `7686` appears with multiple fields in line `114`

**Comment by jenniyanjie** [comment]
@Hydrotoast, you are right, but it is feature 2738 (not 2739)
I spotted 5:2738:0.3651 and 13:2738:0.3651 appears multiple times in the file.

**Comment by tkcrown** [comment]
@jenniyanjie you can find the answer in ffm.cpp line 68:69 and 43:44. The feature index is field-independent.

**Comment by guestwalk** [comment]
This is actually because this tiny data set was subsampled from Kaggle's Criteo competition, and in this competition, we use hashing trick to generate features. The example you gave is due to hashing conflict. We admit this is confusing, and will resolve this issue in next release.
