### ISSUE TITLE
libffm-linear prediction

### ISSUE THREAD

**Issue by GedasZ** [guestwalk/libffm#5]
Hello,

I'm trying to use libffm-linear library. Here are my outputs:

libffm-linear>windows\ffm-train -s 2 -l 0 -k 10 -t 50 -r 0.01 --au
to-stop -p test_data.txt train_data.txt model
iter   tr_logloss   va_logloss
   1      0.25510      0.25017
   2      0.25129      0.24927
   3      0.25070      0.24882
   4      0.25041      0.24843
   5      0.25020      0.24821
   6      0.25005      0.24808
   7      0.24990      0.24801
   8      0.24977      0.24800
   9      0.24968      0.24820
Auto-stop. Use model at 8th iteration.

libffm-linear>windows\ffm-predict test_data.txt model output_file
logloss = 0.34800

Why prediction logloss differs from validation logloss on same file?

**Comment by guestwalk** [comment]
Thanks for the bug report. We will fix it.
